novocliente:
    build: .
    container_name: novocliente
    ports:
        - "80:1521"
    restart: always
    volumes:
        - .:/home
    environment:
        - DATABASE_HOST=$DATABASE_HOST
        - DATABASE_PORT=$DATABASE_PORT
